<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251025172858 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE change_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, request_id VARCHAR(64) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id VARCHAR(255) NOT NULL, action VARCHAR(20) NOT NULL, diff JSON NOT NULL, context JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_entity_timeline ON change_log (entity_type, entity_id, changed_at)');
        $this->addSql('CREATE INDEX idx_user_activity ON change_log (user_id, changed_at)');
        $this->addSql('CREATE INDEX idx_request_group ON change_log (request_id)');
        $this->addSql('CREATE INDEX idx_timeline ON change_log (changed_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE change_log');
    }
}
