<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251024211634 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, address TEXT DEFAULT NULL, parent_location_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1158DD896D6133FE ON stock_location (parent_location_id)');
        $this->addSql('CREATE TABLE stock_lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lot_number VARCHAR(255) DEFAULT NULL, production_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expiration_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, received_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, initial_qty NUMERIC(10, 2) NOT NULL, current_qty NUMERIC(10, 2) NOT NULL, reserved_qty NUMERIC(10, 2) NOT NULL, unit_cost NUMERIC(10, 2) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, stock_target_id INT NOT NULL, vendor_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, stock_receipt_item_id INT DEFAULT NULL, allocated_from_id INT DEFAULT NULL, allocated_to_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7DEF9C8D8D13ED8E ON stock_lot (stock_target_id)');
        $this->addSql('CREATE INDEX IDX_7DEF9C8DF603EE73 ON stock_lot (vendor_id)');
        $this->addSql('CREATE INDEX IDX_7DEF9C8D558FBEB9 ON stock_lot (purchase_id)');
        $this->addSql('CREATE INDEX IDX_7DEF9C8DE08C8C01 ON stock_lot (stock_receipt_item_id)');
        $this->addSql('CREATE INDEX IDX_7DEF9C8D6F9DAB62 ON stock_lot (allocated_from_id)');
        $this->addSql('CREATE INDEX IDX_7DEF9C8DF2D0DFE9 ON stock_lot (allocated_to_id)');
        $this->addSql('CREATE TABLE stock_lot_allocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty NUMERIC(10, 2) NOT NULL, allocation_type VARCHAR(50) NOT NULL, direction VARCHAR(50) NOT NULL, total_cost NUMERIC(10, 2) NOT NULL, allocated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE stock_lot_location_balance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty NUMERIC(10, 2) NOT NULL, reserved_qty NUMERIC(10, 2) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, stock_lot_id INT NOT NULL, location_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B1EA46D62ED7761 ON stock_lot_location_balance (stock_lot_id)');
        $this->addSql('CREATE INDEX IDX_5B1EA46D64D218E ON stock_lot_location_balance (location_id)');
        $this->addSql('CREATE TABLE stock_lot_transfer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty NUMERIC(10, 2) NOT NULL, transfer_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes TEXT NOT NULL, stock_lot_id INT NOT NULL, from_location_id INT NOT NULL, to_location_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C39568E762ED7761 ON stock_lot_transfer (stock_lot_id)');
        $this->addSql('CREATE INDEX IDX_C39568E7980210EB ON stock_lot_transfer (from_location_id)');
        $this->addSql('CREATE INDEX IDX_C39568E728DE1FED ON stock_lot_transfer (to_location_id)');
        $this->addSql('ALTER TABLE stock_location ADD CONSTRAINT FK_1158DD896D6133FE FOREIGN KEY (parent_location_id) REFERENCES stock_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot ADD CONSTRAINT FK_7DEF9C8D8D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot ADD CONSTRAINT FK_7DEF9C8DF603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot ADD CONSTRAINT FK_7DEF9C8D558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot ADD CONSTRAINT FK_7DEF9C8DE08C8C01 FOREIGN KEY (stock_receipt_item_id) REFERENCES stock_receipt_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot ADD CONSTRAINT FK_7DEF9C8D6F9DAB62 FOREIGN KEY (allocated_from_id) REFERENCES stock_lot_allocation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot ADD CONSTRAINT FK_7DEF9C8DF2D0DFE9 FOREIGN KEY (allocated_to_id) REFERENCES stock_lot_allocation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot_location_balance ADD CONSTRAINT FK_5B1EA46D62ED7761 FOREIGN KEY (stock_lot_id) REFERENCES stock_lot (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot_location_balance ADD CONSTRAINT FK_5B1EA46D64D218E FOREIGN KEY (location_id) REFERENCES stock_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot_transfer ADD CONSTRAINT FK_C39568E762ED7761 FOREIGN KEY (stock_lot_id) REFERENCES stock_lot (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot_transfer ADD CONSTRAINT FK_C39568E7980210EB FOREIGN KEY (from_location_id) REFERENCES stock_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_lot_transfer ADD CONSTRAINT FK_C39568E728DE1FED FOREIGN KEY (to_location_id) REFERENCES stock_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_transaction ADD expiration_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD lot_number VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD stock_lot_allocation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD CONSTRAINT FK_ADF9A3E5863A927E FOREIGN KEY (stock_lot_allocation_id) REFERENCES stock_lot_allocation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_ADF9A3E5863A927E ON stock_transaction (stock_lot_allocation_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_location DROP CONSTRAINT FK_1158DD896D6133FE');
        $this->addSql('ALTER TABLE stock_lot DROP CONSTRAINT FK_7DEF9C8D8D13ED8E');
        $this->addSql('ALTER TABLE stock_lot DROP CONSTRAINT FK_7DEF9C8DF603EE73');
        $this->addSql('ALTER TABLE stock_lot DROP CONSTRAINT FK_7DEF9C8D558FBEB9');
        $this->addSql('ALTER TABLE stock_lot DROP CONSTRAINT FK_7DEF9C8DE08C8C01');
        $this->addSql('ALTER TABLE stock_lot DROP CONSTRAINT FK_7DEF9C8D6F9DAB62');
        $this->addSql('ALTER TABLE stock_lot DROP CONSTRAINT FK_7DEF9C8DF2D0DFE9');
        $this->addSql('ALTER TABLE stock_lot_location_balance DROP CONSTRAINT FK_5B1EA46D62ED7761');
        $this->addSql('ALTER TABLE stock_lot_location_balance DROP CONSTRAINT FK_5B1EA46D64D218E');
        $this->addSql('ALTER TABLE stock_lot_transfer DROP CONSTRAINT FK_C39568E762ED7761');
        $this->addSql('ALTER TABLE stock_lot_transfer DROP CONSTRAINT FK_C39568E7980210EB');
        $this->addSql('ALTER TABLE stock_lot_transfer DROP CONSTRAINT FK_C39568E728DE1FED');
        $this->addSql('DROP TABLE stock_location');
        $this->addSql('DROP TABLE stock_lot');
        $this->addSql('DROP TABLE stock_lot_allocation');
        $this->addSql('DROP TABLE stock_lot_location_balance');
        $this->addSql('DROP TABLE stock_lot_transfer');
        $this->addSql('ALTER TABLE stock_transaction DROP CONSTRAINT FK_ADF9A3E5863A927E');
        $this->addSql('DROP INDEX IDX_ADF9A3E5863A927E');
        $this->addSql('ALTER TABLE stock_transaction DROP expiration_date');
        $this->addSql('ALTER TABLE stock_transaction DROP lot_number');
        $this->addSql('ALTER TABLE stock_transaction DROP stock_lot_allocation_id');
    }
}
