<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250912014140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rsvp_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, naughty BOOLEAN NOT NULL, name VARCHAR(255) DEFAULT NULL, guest_count INT DEFAULT NULL, note TEXT DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE stock_target ALTER reorder_point TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE stock_target ALTER reorder_point DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE rsvp_log');
        $this->addSql('ALTER TABLE stock_target ALTER reorder_point TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE stock_target ALTER reorder_point SET DEFAULT \'0.00\'');
    }
}
