<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126023543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE import_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, total_rows INT NOT NULL, processed_rows INT NOT NULL, successful_rows INT NOT NULL, failed_rows INT NOT NULL, error_summary JSON DEFAULT NULL, entity_counts JSON DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, source_file VARCHAR(255) DEFAULT NULL, source_file_path VARCHAR(500) DEFAULT NULL, mapping_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_155EFD1AFABB77CC ON import_batch (mapping_id)');
        $this->addSql('CREATE INDEX idx_import_batch_status ON import_batch (status)');
        $this->addSql('CREATE INDEX idx_import_batch_created_by ON import_batch (created_by)');
        $this->addSql('CREATE INDEX idx_import_batch_started_at ON import_batch (started_at)');
        $this->addSql('CREATE TABLE import_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, row_number INT NOT NULL, error_type VARCHAR(100) NOT NULL, severity VARCHAR(50) NOT NULL, field_name VARCHAR(255) DEFAULT NULL, error_message TEXT NOT NULL, row_data JSON DEFAULT NULL, suggested_fix TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, batch_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_import_error_batch ON import_error (batch_id)');
        $this->addSql('CREATE INDEX idx_import_error_type ON import_error (error_type)');
        $this->addSql('CREATE INDEX idx_import_error_row ON import_error (batch_id, row_number)');
        $this->addSql('CREATE TABLE import_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, entity_type VARCHAR(100) NOT NULL, field_mappings JSON NOT NULL, transformation_rules JSON DEFAULT NULL, validation_rules JSON DEFAULT NULL, default_values JSON DEFAULT NULL, is_active BOOLEAN NOT NULL, is_system_template BOOLEAN NOT NULL, created_by INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_import_mapping_entity_type ON import_mapping (entity_type)');
        $this->addSql('CREATE INDEX idx_import_mapping_active ON import_mapping (is_active)');
        $this->addSql('CREATE TABLE import_mapping_learning (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, column_name VARCHAR(255) NOT NULL, target_field VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, header_fingerprint VARCHAR(64) DEFAULT NULL, success_count INT NOT NULL, failed_suggestions JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_import_mapping_learning_entity_type ON import_mapping_learning (entity_type)');
        $this->addSql('CREATE INDEX idx_import_mapping_learning_fingerprint ON import_mapping_learning (header_fingerprint)');
        $this->addSql('CREATE UNIQUE INDEX unique_column_field_entity ON import_mapping_learning (column_name, target_field, entity_type)');
        $this->addSql('ALTER TABLE import_batch ADD CONSTRAINT FK_155EFD1AFABB77CC FOREIGN KEY (mapping_id) REFERENCES import_mapping (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE import_error ADD CONSTRAINT FK_B08813BFF39EBE7A FOREIGN KEY (batch_id) REFERENCES import_batch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE import_batch DROP CONSTRAINT FK_155EFD1AFABB77CC');
        $this->addSql('ALTER TABLE import_error DROP CONSTRAINT FK_B08813BFF39EBE7A');
        $this->addSql('DROP TABLE import_batch');
        $this->addSql('DROP TABLE import_error');
        $this->addSql('DROP TABLE import_mapping');
        $this->addSql('DROP TABLE import_mapping_learning');
    }
}
