<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251029162932 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE price_alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, alert_type VARCHAR(50) NOT NULL, threshold_value NUMERIC(10, 4) DEFAULT NULL, enabled BOOLEAN NOT NULL, last_triggered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_price NUMERIC(10, 4) NOT NULL, trigger_count INT NOT NULL, notify_users JSON DEFAULT NULL, notify_email VARCHAR(255) NOT NULL, stock_target_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3C344EA18D13ED8E ON price_alert (stock_target_id)');
        $this->addSql('CREATE TABLE recipe_cost_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ingredient_cost NUMERIC(10, 4) NOT NULL, labor_cost NUMERIC(10, 4) NOT NULL, overhead_cost NUMERIC(10, 4) NOT NULL, total_cost NUMERIC(10, 4) NOT NULL, servings NUMERIC(8, 2) NOT NULL, cost_per_serving NUMERIC(10, 4) NOT NULL, suggested_price NUMERIC(10, 4) DEFAULT NULL, target_food_cost_pct NUMERIC(7, 4) DEFAULT NULL, calculation_method VARCHAR(50) NOT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ingredient_breakdown JSON DEFAULT NULL, recipe_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A98404659D8A214 ON recipe_cost_snapshot (recipe_id)');
        $this->addSql('ALTER TABLE price_alert ADD CONSTRAINT FK_3C344EA18D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_cost_snapshot ADD CONSTRAINT FK_A98404659D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE price_alert DROP CONSTRAINT FK_3C344EA18D13ED8E');
        $this->addSql('ALTER TABLE recipe_cost_snapshot DROP CONSTRAINT FK_A98404659D8A214');
        $this->addSql('DROP TABLE price_alert');
        $this->addSql('DROP TABLE recipe_cost_snapshot');
    }
}
