<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250725201422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE katzen_user (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('INSERT INTO katzen_user (id) VALUES (1)');
        $this->addSql('CREATE TABLE profile_user (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('INSERT INTO profile_user (id) VALUES (5), (6)');
        $this->addSql('CREATE TABLE profile_user_site (profile_user_id INT NOT NULL, site_id INT NOT NULL, PRIMARY KEY(profile_user_id, site_id))');
        $this->addSql('CREATE INDEX IDX_AF5DAC5674D00D09 ON profile_user_site (profile_user_id)');
        $this->addSql('CREATE INDEX IDX_AF5DAC56F6BD1646 ON profile_user_site (site_id)');
        $this->addSql('CREATE TABLE recipe_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipe_list_recipe (recipe_list_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(recipe_list_id, recipe_id))');
        $this->addSql('CREATE INDEX IDX_97AA3D7D714A18CB ON recipe_list_recipe (recipe_list_id)');
        $this->addSql('CREATE INDEX IDX_97AA3D7D59D8A214 ON recipe_list_recipe (recipe_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, obj VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, obj_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE katzen_user ADD CONSTRAINT FK_4B6C8C78BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_user ADD CONSTRAINT FK_3B5B59DDBF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_user_site ADD CONSTRAINT FK_AF5DAC5674D00D09 FOREIGN KEY (profile_user_id) REFERENCES profile_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_user_site ADD CONSTRAINT FK_AF5DAC56F6BD1646 FOREIGN KEY (site_id) REFERENCES public.sites (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_list_recipe ADD CONSTRAINT FK_97AA3D7D714A18CB FOREIGN KEY (recipe_list_id) REFERENCES recipe_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_list_recipe ADD CONSTRAINT FK_97AA3D7D59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE user_site');
        $this->addSql('DROP TABLE code_name');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B137F675F31B');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B137F675F31B FOREIGN KEY (author_id) REFERENCES katzen_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD dtype VARCHAR(255) NOT NULL DEFAULT \'katzen_user\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA site_12');
        $this->addSql('CREATE SCHEMA site_11');
        $this->addSql('CREATE TABLE user_site (user_id INT NOT NULL, site_id INT NOT NULL, PRIMARY KEY(user_id, site_id))');
        $this->addSql('CREATE INDEX idx_13c2452df6bd1646 ON user_site (site_id)');
        $this->addSql('CREATE INDEX idx_13c2452da76ed395 ON user_site (user_id)');
        $this->addSql('CREATE TABLE code_name (code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE INDEX idx_cd ON code_name (code)');
        $this->addSql('ALTER TABLE katzen_user DROP CONSTRAINT FK_4B6C8C78BF396750');
        $this->addSql('ALTER TABLE profile_user DROP CONSTRAINT FK_3B5B59DDBF396750');
        $this->addSql('ALTER TABLE profile_user_site DROP CONSTRAINT FK_AF5DAC5674D00D09');
        $this->addSql('ALTER TABLE profile_user_site DROP CONSTRAINT FK_AF5DAC56F6BD1646');
        $this->addSql('ALTER TABLE recipe_list_recipe DROP CONSTRAINT FK_97AA3D7D714A18CB');
        $this->addSql('ALTER TABLE recipe_list_recipe DROP CONSTRAINT FK_97AA3D7D59D8A214');
        $this->addSql('DROP TABLE katzen_user');
        $this->addSql('DROP TABLE profile_user');
        $this->addSql('DROP TABLE profile_user_site');
        $this->addSql('DROP TABLE recipe_list');
        $this->addSql('DROP TABLE recipe_list_recipe');
        $this->addSql('DROP TABLE tag');
        $this->addSql('ALTER TABLE "user" DROP dtype');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT fk_da88b137f675f31b');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT fk_da88b137f675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
