<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251028210423 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE plate_costing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, menu_item_name VARCHAR(255) NOT NULL, current_cost NUMERIC(10, 4) NOT NULL, current_price NUMERIC(10, 2) NOT NULL, current_food_cost_pct NUMERIC(5, 2) NOT NULL, target_price NUMERIC(10, 2) DEFAULT NULL, target_food_cost_pct NUMERIC(5, 2) DEFAULT NULL, target_gp_pct NUMERIC(5, 2) DEFAULT NULL, cost_status VARCHAR(50) NOT NULL, price_last_updated DATE DEFAULT NULL, alert_threshold_pct NUMERIC(5, 2) NOT NULL, alert_enabled BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_plate_costing_status ON plate_costing (cost_status)');
        $this->addSql('CREATE UNIQUE INDEX unique_recipe_costing ON plate_costing (recipe_id)');
        $this->addSql('CREATE TABLE price_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unit_price NUMERIC(10, 4) NOT NULL, unit_of_measure VARCHAR(50) NOT NULL, effective_date DATE NOT NULL, source_type VARCHAR(50) NOT NULL, source_id INT DEFAULT NULL, quantity_purchased NUMERIC(10, 3) DEFAULT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recorded_by INT DEFAULT NULL, vendor_id INT NOT NULL, stock_target_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4C9CB817F603EE73 ON price_history (vendor_id)');
        $this->addSql('CREATE INDEX IDX_4C9CB8178D13ED8E ON price_history (stock_target_id)');
        $this->addSql('CREATE INDEX idx_price_history_vendor_target ON price_history (vendor_id, stock_target_id)');
        $this->addSql('CREATE INDEX idx_price_history_effective_date ON price_history (effective_date)');
        $this->addSql('CREATE UNIQUE INDEX unique_price_point ON price_history (vendor_id, stock_target_id, effective_date, source_type, source_id)');
        $this->addSql('CREATE TABLE vendor_credit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, credit_number VARCHAR(100) NOT NULL, credit_date DATE NOT NULL, credit_amount NUMERIC(10, 2) NOT NULL, amount_applied NUMERIC(10, 2) NOT NULL, reason TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vendor_id INT NOT NULL, original_invoice_id INT DEFAULT NULL, stock_receipt_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A0B696CF603EE73 ON vendor_credit (vendor_id)');
        $this->addSql('CREATE INDEX IDX_6A0B696C443E8669 ON vendor_credit (original_invoice_id)');
        $this->addSql('CREATE INDEX IDX_6A0B696C85155F3A ON vendor_credit (stock_receipt_id)');
        $this->addSql('CREATE INDEX idx_vendor_credit_status ON vendor_credit (status)');
        $this->addSql('CREATE UNIQUE INDEX unique_vendor_credit ON vendor_credit (vendor_id, credit_number)');
        $this->addSql('CREATE TABLE vendor_credit_application (vendor_credit_id INT NOT NULL, vendor_invoice_id INT NOT NULL, PRIMARY KEY(vendor_credit_id, vendor_invoice_id))');
        $this->addSql('CREATE INDEX IDX_CD8A16C6461FE78 ON vendor_credit_application (vendor_credit_id)');
        $this->addSql('CREATE INDEX IDX_CD8A16C6B3FC259A ON vendor_credit_application (vendor_invoice_id)');
        $this->addSql('CREATE TABLE vendor_invoice_receipt (vendor_invoice_id INT NOT NULL, stock_receipt_id INT NOT NULL, PRIMARY KEY(vendor_invoice_id, stock_receipt_id))');
        $this->addSql('CREATE INDEX IDX_FAF0CD2EB3FC259A ON vendor_invoice_receipt (vendor_invoice_id)');
        $this->addSql('CREATE INDEX IDX_FAF0CD2E85155F3A ON vendor_invoice_receipt (stock_receipt_id)');
        $this->addSql('ALTER TABLE plate_costing ADD CONSTRAINT FK_1AAF564A59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE price_history ADD CONSTRAINT FK_4C9CB817F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE price_history ADD CONSTRAINT FK_4C9CB8178D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_credit ADD CONSTRAINT FK_6A0B696CF603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_credit ADD CONSTRAINT FK_6A0B696C443E8669 FOREIGN KEY (original_invoice_id) REFERENCES vendor_invoice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_credit ADD CONSTRAINT FK_6A0B696C85155F3A FOREIGN KEY (stock_receipt_id) REFERENCES stock_receipt (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_credit_application ADD CONSTRAINT FK_CD8A16C6461FE78 FOREIGN KEY (vendor_credit_id) REFERENCES vendor_credit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_credit_application ADD CONSTRAINT FK_CD8A16C6B3FC259A FOREIGN KEY (vendor_invoice_id) REFERENCES vendor_invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice_receipt ADD CONSTRAINT FK_FAF0CD2EB3FC259A FOREIGN KEY (vendor_invoice_id) REFERENCES vendor_invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice_receipt ADD CONSTRAINT FK_FAF0CD2E85155F3A FOREIGN KEY (stock_receipt_id) REFERENCES stock_receipt (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice ADD invoice_number VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD invoice_date DATE NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD due_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD subtotal NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD tax_amount NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD shipping_amount NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD discount_amount NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD total_amount NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD amount_paid NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD status VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD approval_status VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD approved_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD reconciled BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD variance_total NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD variance_notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD source_type VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD ocr_confidence NUMERIC(3, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD original_file_path VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD created_by INT NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD posted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD vendor_id INT NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD purchase_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice ADD CONSTRAINT FK_8E122F2BF603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice ADD CONSTRAINT FK_8E122F2B558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_8E122F2BF603EE73 ON vendor_invoice (vendor_id)');
        $this->addSql('CREATE INDEX IDX_8E122F2B558FBEB9 ON vendor_invoice (purchase_id)');
        $this->addSql('CREATE INDEX idx_vendor_invoice_status ON vendor_invoice (status)');
        $this->addSql('CREATE INDEX idx_vendor_invoice_due_date ON vendor_invoice (due_date)');
        $this->addSql('CREATE UNIQUE INDEX unique_vendor_invoice ON vendor_invoice (vendor_id, invoice_number)');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD description TEXT NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD quantity NUMERIC(10, 3) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD unit_of_measure VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD unit_price NUMERIC(10, 4) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD line_total NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD cost_center VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD department VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD expected_unit_price NUMERIC(10, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD price_variance_pct NUMERIC(5, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD variance_flagged BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD vendor_invoice_id INT NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD stock_target_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD expense_account_id INT NOT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD stock_receipt_item_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD purchase_item_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD CONSTRAINT FK_B6DC36A3B3FC259A FOREIGN KEY (vendor_invoice_id) REFERENCES vendor_invoice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD CONSTRAINT FK_B6DC36A38D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD CONSTRAINT FK_B6DC36A32B7F60B3 FOREIGN KEY (expense_account_id) REFERENCES account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD CONSTRAINT FK_B6DC36A3E08C8C01 FOREIGN KEY (stock_receipt_item_id) REFERENCES stock_receipt_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vendor_invoice_item ADD CONSTRAINT FK_B6DC36A39B59827 FOREIGN KEY (purchase_item_id) REFERENCES purchase_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_B6DC36A3E08C8C01 ON vendor_invoice_item (stock_receipt_item_id)');
        $this->addSql('CREATE INDEX IDX_B6DC36A39B59827 ON vendor_invoice_item (purchase_item_id)');
        $this->addSql('CREATE INDEX idx_vendor_invoice_item_invoice ON vendor_invoice_item (vendor_invoice_id)');
        $this->addSql('CREATE INDEX idx_vendor_invoice_item_stock_target ON vendor_invoice_item (stock_target_id)');
        $this->addSql('CREATE INDEX idx_vendor_invoice_item_expense_account ON vendor_invoice_item (expense_account_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE plate_costing DROP CONSTRAINT FK_1AAF564A59D8A214');
        $this->addSql('ALTER TABLE price_history DROP CONSTRAINT FK_4C9CB817F603EE73');
        $this->addSql('ALTER TABLE price_history DROP CONSTRAINT FK_4C9CB8178D13ED8E');
        $this->addSql('ALTER TABLE vendor_credit DROP CONSTRAINT FK_6A0B696CF603EE73');
        $this->addSql('ALTER TABLE vendor_credit DROP CONSTRAINT FK_6A0B696C443E8669');
        $this->addSql('ALTER TABLE vendor_credit DROP CONSTRAINT FK_6A0B696C85155F3A');
        $this->addSql('ALTER TABLE vendor_credit_application DROP CONSTRAINT FK_CD8A16C6461FE78');
        $this->addSql('ALTER TABLE vendor_credit_application DROP CONSTRAINT FK_CD8A16C6B3FC259A');
        $this->addSql('ALTER TABLE vendor_invoice_receipt DROP CONSTRAINT FK_FAF0CD2EB3FC259A');
        $this->addSql('ALTER TABLE vendor_invoice_receipt DROP CONSTRAINT FK_FAF0CD2E85155F3A');
        $this->addSql('DROP TABLE plate_costing');
        $this->addSql('DROP TABLE price_history');
        $this->addSql('DROP TABLE vendor_credit');
        $this->addSql('DROP TABLE vendor_credit_application');
        $this->addSql('DROP TABLE vendor_invoice_receipt');
        $this->addSql('ALTER TABLE vendor_invoice DROP CONSTRAINT FK_8E122F2BF603EE73');
        $this->addSql('ALTER TABLE vendor_invoice DROP CONSTRAINT FK_8E122F2B558FBEB9');
        $this->addSql('DROP INDEX IDX_8E122F2BF603EE73');
        $this->addSql('DROP INDEX IDX_8E122F2B558FBEB9');
        $this->addSql('DROP INDEX idx_vendor_invoice_status');
        $this->addSql('DROP INDEX idx_vendor_invoice_due_date');
        $this->addSql('DROP INDEX unique_vendor_invoice');
        $this->addSql('ALTER TABLE vendor_invoice DROP invoice_number');
        $this->addSql('ALTER TABLE vendor_invoice DROP invoice_date');
        $this->addSql('ALTER TABLE vendor_invoice DROP due_date');
        $this->addSql('ALTER TABLE vendor_invoice DROP subtotal');
        $this->addSql('ALTER TABLE vendor_invoice DROP tax_amount');
        $this->addSql('ALTER TABLE vendor_invoice DROP shipping_amount');
        $this->addSql('ALTER TABLE vendor_invoice DROP discount_amount');
        $this->addSql('ALTER TABLE vendor_invoice DROP total_amount');
        $this->addSql('ALTER TABLE vendor_invoice DROP amount_paid');
        $this->addSql('ALTER TABLE vendor_invoice DROP status');
        $this->addSql('ALTER TABLE vendor_invoice DROP approval_status');
        $this->addSql('ALTER TABLE vendor_invoice DROP approved_by');
        $this->addSql('ALTER TABLE vendor_invoice DROP approved_at');
        $this->addSql('ALTER TABLE vendor_invoice DROP reconciled');
        $this->addSql('ALTER TABLE vendor_invoice DROP variance_total');
        $this->addSql('ALTER TABLE vendor_invoice DROP variance_notes');
        $this->addSql('ALTER TABLE vendor_invoice DROP source_type');
        $this->addSql('ALTER TABLE vendor_invoice DROP ocr_confidence');
        $this->addSql('ALTER TABLE vendor_invoice DROP original_file_path');
        $this->addSql('ALTER TABLE vendor_invoice DROP created_by');
        $this->addSql('ALTER TABLE vendor_invoice DROP created_at');
        $this->addSql('ALTER TABLE vendor_invoice DROP updated_at');
        $this->addSql('ALTER TABLE vendor_invoice DROP posted_at');
        $this->addSql('ALTER TABLE vendor_invoice DROP notes');
        $this->addSql('ALTER TABLE vendor_invoice DROP vendor_id');
        $this->addSql('ALTER TABLE vendor_invoice DROP purchase_id');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP CONSTRAINT FK_B6DC36A3B3FC259A');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP CONSTRAINT FK_B6DC36A38D13ED8E');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP CONSTRAINT FK_B6DC36A32B7F60B3');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP CONSTRAINT FK_B6DC36A3E08C8C01');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP CONSTRAINT FK_B6DC36A39B59827');
        $this->addSql('DROP INDEX IDX_B6DC36A3E08C8C01');
        $this->addSql('DROP INDEX IDX_B6DC36A39B59827');
        $this->addSql('DROP INDEX idx_vendor_invoice_item_invoice');
        $this->addSql('DROP INDEX idx_vendor_invoice_item_stock_target');
        $this->addSql('DROP INDEX idx_vendor_invoice_item_expense_account');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP description');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP quantity');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP unit_of_measure');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP unit_price');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP line_total');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP cost_center');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP department');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP expected_unit_price');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP price_variance_pct');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP variance_flagged');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP notes');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP vendor_invoice_id');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP stock_target_id');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP expense_account_id');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP stock_receipt_item_id');
        $this->addSql('ALTER TABLE vendor_invoice_item DROP purchase_item_id');
    }
}
