<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222170447 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE document_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, referer VARCHAR(500) DEFAULT NULL, document_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_docview_document ON document_view (document_id)');
        $this->addSql('CREATE INDEX idx_docview_date ON document_view (viewed_at)');
        $this->addSql('ALTER TABLE document_view ADD CONSTRAINT FK_5949271DC33F7837 FOREIGN KEY (document_id) REFERENCES research_document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE document_view DROP CONSTRAINT FK_5949271DC33F7837');
        $this->addSql('DROP TABLE document_view');
    }
}
