<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250328154821 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE post_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_url TEXT NOT NULL, etag TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_522688B04B89032C ON post_image (post_id)');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B04B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE blog_post ADD title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD subtitle VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD summary TEXT NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD text_content TEXT NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD content TEXT NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD author_id INT NOT NULL');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01DF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_BA5AE01DF675F31B ON blog_post (author_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE post_image DROP CONSTRAINT FK_522688B04B89032C');
        $this->addSql('DROP TABLE post_image');
        $this->addSql('ALTER TABLE blog_post DROP CONSTRAINT FK_BA5AE01DF675F31B');
        $this->addSql('DROP INDEX IDX_BA5AE01DF675F31B');
        $this->addSql('ALTER TABLE blog_post DROP title');
        $this->addSql('ALTER TABLE blog_post DROP subtitle');
        $this->addSql('ALTER TABLE blog_post DROP summary');
        $this->addSql('ALTER TABLE blog_post DROP text_content');
        $this->addSql('ALTER TABLE blog_post DROP content');
        $this->addSql('ALTER TABLE blog_post DROP created_at');
        $this->addSql('ALTER TABLE blog_post DROP updated_at');
        $this->addSql('ALTER TABLE blog_post DROP author_id');
    }
}
