<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250310152717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(1000) NOT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipe_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ingredient_id INT NOT NULL, supply_type VARCHAR(255) NOT NULL, supply_id INT NOT NULL, quantity NUMERIC(8, 2) NOT NULL, note VARCHAR(1000) DEFAULT NULL, recipe_id_id INT NOT NULL, unit_id_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_22D1FE1369574A48 ON recipe_ingredient (recipe_id_id)');
        $this->addSql('CREATE INDEX IDX_22D1FE13F476E05C ON recipe_ingredient (unit_id_id)');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE1369574A48 FOREIGN KEY (recipe_id_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE13F476E05C FOREIGN KEY (unit_id_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_instruction ADD section_number INT NOT NULL');
        $this->addSql('ALTER TABLE recipe_instruction ADD step_number INT NOT NULL');
        $this->addSql('ALTER TABLE recipe_instruction ADD description VARCHAR(1000) NOT NULL');
        $this->addSql('ALTER TABLE recipe_instruction ADD prep_time NUMERIC(6, 2) NOT NULL');
        $this->addSql('ALTER TABLE recipe_instruction ADD cook_time NUMERIC(6, 2) NOT NULL');
        $this->addSql('ALTER TABLE recipe_instruction ADD wait_time NUMERIC(6, 2) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE1369574A48');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE13F476E05C');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE recipe_ingredient');
        $this->addSql('ALTER TABLE recipe_instruction DROP section_number');
        $this->addSql('ALTER TABLE recipe_instruction DROP step_number');
        $this->addSql('ALTER TABLE recipe_instruction DROP description');
        $this->addSql('ALTER TABLE recipe_instruction DROP prep_time');
        $this->addSql('ALTER TABLE recipe_instruction DROP cook_time');
        $this->addSql('ALTER TABLE recipe_instruction DROP wait_time');
    }
}
