<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250325124543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE item_upc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, barcode VARCHAR(255) NOT NULL, quantity NUMERIC(10, 4) NOT NULL, item_id INT NOT NULL, unit_id INT NOT NULL, item_variant_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B1EA418F126F525E ON item_upc (item_id)');
        $this->addSql('CREATE INDEX IDX_B1EA418FF8BD700D ON item_upc (unit_id)');
        $this->addSql('CREATE INDEX IDX_B1EA418F86D881A5 ON item_upc (item_variant_id)');
        $this->addSql('CREATE TABLE item_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, item_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA1E99F9126F525E ON item_variant (item_id)');
        $this->addSql('ALTER TABLE item_upc ADD CONSTRAINT FK_B1EA418F126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_upc ADD CONSTRAINT FK_B1EA418FF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_upc ADD CONSTRAINT FK_B1EA418F86D881A5 FOREIGN KEY (item_variant_id) REFERENCES item_variant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_variant ADD CONSTRAINT FK_FA1E99F9126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE item_upc DROP CONSTRAINT FK_B1EA418F126F525E');
        $this->addSql('ALTER TABLE item_upc DROP CONSTRAINT FK_B1EA418FF8BD700D');
        $this->addSql('ALTER TABLE item_upc DROP CONSTRAINT FK_B1EA418F86D881A5');
        $this->addSql('ALTER TABLE item_variant DROP CONSTRAINT FK_FA1E99F9126F525E');
        $this->addSql('DROP TABLE item_upc');
        $this->addSql('DROP TABLE item_variant');
    }
}
