<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250712160609 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blog_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(1000) NOT NULL, summary TEXT NOT NULL, text_content TEXT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, featured_image VARCHAR(255) DEFAULT NULL, author_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BA5AE01DF675F31B ON blog_post (author_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, schema JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FEC530A912469DE2 ON content (category_id)');
        $this->addSql('CREATE TABLE invite_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(6) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, event TEXT DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fooddb_id VARCHAR(255) DEFAULT NULL, scientific_name VARCHAR(255) DEFAULT NULL, subcategory VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE item_upc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, barcode VARCHAR(255) NOT NULL, quantity NUMERIC(10, 4) NOT NULL, item_id INT NOT NULL, unit_id INT NOT NULL, item_variant_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B1EA418F126F525E ON item_upc (item_id)');
        $this->addSql('CREATE INDEX IDX_B1EA418FF8BD700D ON item_upc (unit_id)');
        $this->addSql('CREATE INDEX IDX_B1EA418F86D881A5 ON item_upc (item_variant_id)');
        $this->addSql('CREATE TABLE item_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, item_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA1E99F9126F525E ON item_variant (item_id)');
        $this->addSql('CREATE TABLE katzen_user (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, data JSONB NOT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, page_type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE post_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_url TEXT NOT NULL, etag TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_522688B04B89032C ON post_image (post_id)');
        $this->addSql('CREATE TABLE profile_user (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE profile_user_site (profile_user_id INT NOT NULL, site_id INT NOT NULL, PRIMARY KEY(profile_user_id, site_id))');
        $this->addSql('CREATE INDEX IDX_AF5DAC5674D00D09 ON profile_user_site (profile_user_id)');
        $this->addSql('CREATE INDEX IDX_AF5DAC56F6BD1646 ON profile_user_site (site_id)');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, summary TEXT DEFAULT NULL, serving_min_qty INT NOT NULL, serving_max_qty INT DEFAULT NULL, prep_time NUMERIC(6, 2) NOT NULL, cook_time NUMERIC(6, 2) NOT NULL, wait_time NUMERIC(6, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT NOT NULL, status VARCHAR(255) NOT NULL, is_public BOOLEAN NOT NULL, author_id INT NOT NULL, serving_unit_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DA88B137F675F31B ON recipe (author_id)');
        $this->addSql('CREATE INDEX IDX_DA88B137EC3181A7 ON recipe (serving_unit_id)');
        $this->addSql('CREATE TABLE recipe_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, supply_type VARCHAR(255) NOT NULL, supply_id INT NOT NULL, quantity NUMERIC(8, 2) NOT NULL, note VARCHAR(1000) DEFAULT NULL, recipe_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_22D1FE1359D8A214 ON recipe_ingredient (recipe_id)');
        $this->addSql('CREATE INDEX IDX_22D1FE13F8BD700D ON recipe_ingredient (unit_id)');
        $this->addSql('CREATE TABLE recipe_instruction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, section_number INT NOT NULL, step_number INT NOT NULL, description VARCHAR(1000) NOT NULL, prep_time NUMERIC(6, 2) NOT NULL, cook_time NUMERIC(6, 2) NOT NULL, wait_time NUMERIC(6, 2) NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF48AF3259D8A214 ON recipe_instruction (recipe_id)');
        $this->addSql('CREATE TABLE recipient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipient_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, event TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, y_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6F83D11CAE732C28 ON recipient_event (y_id)');
        $this->addSql('CREATE TABLE revision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, table_name VARCHAR(255) NOT NULL, data JSON NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE public.sites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, is_production BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8DD1CB07A7A91E0B ON public.sites (domain)');
        $this->addSql('CREATE TABLE unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, abbreviation VARCHAR(10) NOT NULL, category VARCHAR(255) DEFAULT NULL, base_unit_id INT NOT NULL, conversion_factor NUMERIC(8, 4) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL, sess_data BYTEA NOT NULL, sess_lifetime INT NOT NULL, sess_time INT NOT NULL, PRIMARY KEY(sess_id))');
        $this->addSql('CREATE INDEX sess_lifetime_idx ON sessions (sess_lifetime)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01DF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A912469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_upc ADD CONSTRAINT FK_B1EA418F126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_upc ADD CONSTRAINT FK_B1EA418FF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_upc ADD CONSTRAINT FK_B1EA418F86D881A5 FOREIGN KEY (item_variant_id) REFERENCES item_variant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_variant ADD CONSTRAINT FK_FA1E99F9126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE katzen_user ADD CONSTRAINT FK_4B6C8C78BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B04B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_user ADD CONSTRAINT FK_3B5B59DDBF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_user_site ADD CONSTRAINT FK_AF5DAC5674D00D09 FOREIGN KEY (profile_user_id) REFERENCES profile_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_user_site ADD CONSTRAINT FK_AF5DAC56F6BD1646 FOREIGN KEY (site_id) REFERENCES public.sites (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B137F675F31B FOREIGN KEY (author_id) REFERENCES katzen_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B137EC3181A7 FOREIGN KEY (serving_unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE1359D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE13F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_instruction ADD CONSTRAINT FK_AF48AF3259D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipient_event ADD CONSTRAINT FK_6F83D11CAE732C28 FOREIGN KEY (y_id) REFERENCES recipient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blog_post DROP CONSTRAINT FK_BA5AE01DF675F31B');
        $this->addSql('ALTER TABLE content DROP CONSTRAINT FK_FEC530A912469DE2');
        $this->addSql('ALTER TABLE item_upc DROP CONSTRAINT FK_B1EA418F126F525E');
        $this->addSql('ALTER TABLE item_upc DROP CONSTRAINT FK_B1EA418FF8BD700D');
        $this->addSql('ALTER TABLE item_upc DROP CONSTRAINT FK_B1EA418F86D881A5');
        $this->addSql('ALTER TABLE item_variant DROP CONSTRAINT FK_FA1E99F9126F525E');
        $this->addSql('ALTER TABLE katzen_user DROP CONSTRAINT FK_4B6C8C78BF396750');
        $this->addSql('ALTER TABLE post_image DROP CONSTRAINT FK_522688B04B89032C');
        $this->addSql('ALTER TABLE profile_user DROP CONSTRAINT FK_3B5B59DDBF396750');
        $this->addSql('ALTER TABLE profile_user_site DROP CONSTRAINT FK_AF5DAC5674D00D09');
        $this->addSql('ALTER TABLE profile_user_site DROP CONSTRAINT FK_AF5DAC56F6BD1646');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B137F675F31B');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B137EC3181A7');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE1359D8A214');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE13F8BD700D');
        $this->addSql('ALTER TABLE recipe_instruction DROP CONSTRAINT FK_AF48AF3259D8A214');
        $this->addSql('ALTER TABLE recipient_event DROP CONSTRAINT FK_6F83D11CAE732C28');
        $this->addSql('DROP TABLE blog_post');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE content');
        $this->addSql('DROP TABLE invite_log');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_upc');
        $this->addSql('DROP TABLE item_variant');
        $this->addSql('DROP TABLE katzen_user');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE post_image');
        $this->addSql('DROP TABLE profile_user');
        $this->addSql('DROP TABLE profile_user_site');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE recipe_ingredient');
        $this->addSql('DROP TABLE recipe_instruction');
        $this->addSql('DROP TABLE recipient');
        $this->addSql('DROP TABLE recipient_event');
        $this->addSql('DROP TABLE revision');
        $this->addSql('DROP TABLE public.sites');
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE sessions');
    }
}
