<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260820120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create poem, play, essay, album, and song tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE poem (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, collection_name VARCHAR(255) DEFAULT NULL, blurb TEXT DEFAULT NULL, body TEXT DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, file_path VARCHAR(500) DEFAULT NULL, original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POEM_SLUG ON poem (slug)');

        $this->addSql('CREATE TABLE play (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, blurb TEXT DEFAULT NULL, description TEXT DEFAULT NULL, genre VARCHAR(255) DEFAULT NULL, runtime_minutes INT DEFAULT NULL, premiere_year INT DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, file_path VARCHAR(500) DEFAULT NULL, original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PLAY_SLUG ON play (slug)');

        $this->addSql('CREATE TABLE essay (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, blurb TEXT DEFAULT NULL, body TEXT DEFAULT NULL, source VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, file_path VARCHAR(500) DEFAULT NULL, original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ESSAY_SLUG ON essay (slug)');

        $this->addSql('CREATE TABLE album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, release_year INT DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ALBUM_SLUG ON album (slug)');

        $this->addSql('CREATE TABLE song (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, album_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, track_number INT DEFAULT NULL, duration_seconds INT DEFAULT NULL, lyrics TEXT DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, audio_file_path VARCHAR(500) DEFAULT NULL, audio_original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SONG_SLUG ON song (slug)');
        $this->addSql('CREATE INDEX IDX_SONG_ALBUM ON song (album_id)');
        $this->addSql('ALTER TABLE song ADD CONSTRAINT FK_SONG_ALBUM FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE song DROP CONSTRAINT FK_SONG_ALBUM');
        $this->addSql('DROP TABLE song');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE essay');
        $this->addSql('DROP TABLE play');
        $this->addSql('DROP TABLE poem');
    }
}
