<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223005834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE document_view DROP CONSTRAINT fk_5949271dc33f7837');
        $this->addSql('DROP TABLE document_view');
        $this->addSql('DROP TABLE reading_list_item');
        $this->addSql('DROP TABLE research_document');
        $this->addSql('CREATE TABLE profile_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, authors VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, source VARCHAR(500) DEFAULT NULL, abstract TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, file_path VARCHAR(500) DEFAULT NULL, original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE profile_document_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, referer VARCHAR(500) DEFAULT NULL, document_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_docview_document ON profile_document_view (document_id)');
        $this->addSql('CREATE INDEX idx_docview_date ON profile_document_view (viewed_at)');
        $this->addSql('CREATE TABLE profile_reading_list_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, author VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, isbn VARCHAR(20) DEFAULT NULL, status VARCHAR(20) NOT NULL, rating INT DEFAULT NULL, notes TEXT DEFAULT NULL, date_finished DATE DEFAULT NULL, tags JSON DEFAULT NULL, cover_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE profile_document_view ADD CONSTRAINT FK_774A82DDC33F7837 FOREIGN KEY (document_id) REFERENCES profile_document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE profile_document_view DROP CONSTRAINT FK_774A82DDC33F7837');
        $this->addSql('DROP TABLE profile_document');
        $this->addSql('DROP TABLE profile_document_view');
        $this->addSql('DROP TABLE profile_reading_list_item');
        $this->addSql('CREATE TABLE document_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, referer VARCHAR(500) DEFAULT NULL, document_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_docview_date ON document_view (viewed_at)');
        $this->addSql('CREATE INDEX idx_docview_document ON document_view (document_id)');
        $this->addSql('CREATE TABLE reading_list_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, author VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, isbn VARCHAR(20) DEFAULT NULL, status VARCHAR(20) NOT NULL, rating INT DEFAULT NULL, notes TEXT DEFAULT NULL, date_finished DATE DEFAULT NULL, tags JSON DEFAULT NULL, cover_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE research_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, authors VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, source VARCHAR(500) DEFAULT NULL, abstract TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, file_path VARCHAR(500) DEFAULT NULL, original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE document_view ADD CONSTRAINT fk_5949271dc33f7837 FOREIGN KEY (document_id) REFERENCES research_document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
