<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222162937 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE reading_list_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, author VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, isbn VARCHAR(20) DEFAULT NULL, status VARCHAR(20) NOT NULL, rating INT DEFAULT NULL, notes TEXT DEFAULT NULL, date_finished DATE DEFAULT NULL, tags JSON DEFAULT NULL, cover_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE research_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, authors VARCHAR(500) DEFAULT NULL, year INT DEFAULT NULL, source VARCHAR(500) DEFAULT NULL, abstract TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, file_path VARCHAR(500) DEFAULT NULL, original_file_name VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE reading_list_item');
        $this->addSql('DROP TABLE research_document');
    }
}
