<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250715123904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipe_list_recipe (recipe_list_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(recipe_list_id, recipe_id))');
        $this->addSql('CREATE INDEX IDX_97AA3D7D714A18CB ON recipe_list_recipe (recipe_list_id)');
        $this->addSql('CREATE INDEX IDX_97AA3D7D59D8A214 ON recipe_list_recipe (recipe_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, obj VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE recipe_list_recipe ADD CONSTRAINT FK_97AA3D7D714A18CB FOREIGN KEY (recipe_list_id) REFERENCES recipe_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_list_recipe ADD CONSTRAINT FK_97AA3D7D59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_list_recipe DROP CONSTRAINT FK_97AA3D7D714A18CB');
        $this->addSql('ALTER TABLE recipe_list_recipe DROP CONSTRAINT FK_97AA3D7D59D8A214');
        $this->addSql('DROP TABLE recipe_list');
        $this->addSql('DROP TABLE recipe_list_recipe');
        $this->addSql('DROP TABLE tag');
    }
}
