<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251021162022 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(15) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7D3656A4727ACA70 ON account (parent_id)');
        $this->addSql('CREATE TABLE ledger_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, transaction_type VARCHAR(255) NOT NULL, reference_type VARCHAR(255) NOT NULL, reference_id VARCHAR(255) NOT NULL, is_reconciled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ledger_entry_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, debit NUMERIC(10, 2) NOT NULL, credit NUMERIC(10, 2) NOT NULL, memo TEXT DEFAULT NULL, entry_id INT NOT NULL, account_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EB0F604DBA364942 ON ledger_entry_line (entry_id)');
        $this->addSql('CREATE INDEX IDX_EB0F604D9B6B5FBA ON ledger_entry_line (account_id)');
        $this->addSql('CREATE TABLE order_invoice (order_id INT NOT NULL, invoice_id INT NOT NULL, PRIMARY KEY(order_id, invoice_id))');
        $this->addSql('CREATE INDEX IDX_661FBE0F8D9F6D38 ON order_invoice (order_id)');
        $this->addSql('CREATE INDEX IDX_661FBE0F2989F1FD ON order_invoice (invoice_id)');
        $this->addSql('CREATE TABLE purchase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, po_number VARCHAR(255) NOT NULL, order_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expected_delivery TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, subtotal NUMERIC(10, 2) NOT NULL, tax_amount NUMERIC(10, 2) NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE purchase_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty_ordered NUMERIC(10, 2) NOT NULL, qty_received NUMERIC(10, 2) NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, line_total NUMERIC(10, 2) NOT NULL, purchase_id INT NOT NULL, stock_target_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6FA8ED7D558FBEB9 ON purchase_item (purchase_id)');
        $this->addSql('CREATE INDEX IDX_6FA8ED7D8D13ED8E ON purchase_item (stock_target_id)');
        $this->addSql('CREATE TABLE stock_receipt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE stock_receipt_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE vendor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE vendor_invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE vendor_invoice_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4727ACA70 FOREIGN KEY (parent_id) REFERENCES account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ledger_entry_line ADD CONSTRAINT FK_EB0F604DBA364942 FOREIGN KEY (entry_id) REFERENCES ledger_entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ledger_entry_line ADD CONSTRAINT FK_EB0F604D9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_invoice ADD CONSTRAINT FK_661FBE0F8D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_invoice ADD CONSTRAINT FK_661FBE0F2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE purchase_item ADD CONSTRAINT FK_6FA8ED7D558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE purchase_item ADD CONSTRAINT FK_6FA8ED7D8D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer ADD payment_terms VARCHAR(50) NOT NULL DEFAULT \'due_on_recipt\'');
        $this->addSql('ALTER TABLE customer ADD ar_balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT fk_906517448d9f6d38');
        $this->addSql('DROP INDEX idx_906517448d9f6d38');
        $this->addSql('ALTER TABLE invoice DROP order_id');
        $this->addSql('ALTER TABLE "order" ADD subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00');
        $this->addSql('ALTER TABLE "order" ADD tax_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00');
        $this->addSql('ALTER TABLE "order" ADD total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00');
        $this->addSql('ALTER TABLE "order" ADD fulfillment_status VARCHAR(50) NOT NULL DEFAULT \'unfulfilled\'');
        $this->addSql('ALTER TABLE "order" ADD fulfilled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE order_item ADD cogs NUMERIC(10, 2) NOT NULL DEFAULT 0.00');
        $this->addSql('ALTER TABLE order_item ADD fulfilled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD effective_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW()');
        $this->addSql('ALTER TABLE stock_transaction ADD recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW()');
        $this->addSql('ALTER TABLE stock_transaction ADD unit_cost NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD status VARCHAR(50) NOT NULL DEFAULT \'peending\'');
        $this->addSql('ALTER TABLE stock_transaction ADD batch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD ledger_entry_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_transaction ADD CONSTRAINT FK_ADF9A3E5EB264CB8 FOREIGN KEY (ledger_entry_id) REFERENCES ledger_entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_ADF9A3E5EB264CB8 ON stock_transaction (ledger_entry_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A4727ACA70');
        $this->addSql('ALTER TABLE ledger_entry_line DROP CONSTRAINT FK_EB0F604DBA364942');
        $this->addSql('ALTER TABLE ledger_entry_line DROP CONSTRAINT FK_EB0F604D9B6B5FBA');
        $this->addSql('ALTER TABLE order_invoice DROP CONSTRAINT FK_661FBE0F8D9F6D38');
        $this->addSql('ALTER TABLE order_invoice DROP CONSTRAINT FK_661FBE0F2989F1FD');
        $this->addSql('ALTER TABLE purchase_item DROP CONSTRAINT FK_6FA8ED7D558FBEB9');
        $this->addSql('ALTER TABLE purchase_item DROP CONSTRAINT FK_6FA8ED7D8D13ED8E');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE ledger_entry');
        $this->addSql('DROP TABLE ledger_entry_line');
        $this->addSql('DROP TABLE order_invoice');
        $this->addSql('DROP TABLE purchase');
        $this->addSql('DROP TABLE purchase_item');
        $this->addSql('DROP TABLE stock_receipt');
        $this->addSql('DROP TABLE stock_receipt_item');
        $this->addSql('DROP TABLE vendor');
        $this->addSql('DROP TABLE vendor_invoice');
        $this->addSql('DROP TABLE vendor_invoice_item');
        $this->addSql('ALTER TABLE invoice ADD order_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT fk_906517448d9f6d38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_906517448d9f6d38 ON invoice (order_id)');
        $this->addSql('ALTER TABLE order_item DROP cogs');
        $this->addSql('ALTER TABLE order_item DROP fulfilled_at');
        $this->addSql('ALTER TABLE stock_transaction DROP CONSTRAINT FK_ADF9A3E5EB264CB8');
        $this->addSql('DROP INDEX IDX_ADF9A3E5EB264CB8');
        $this->addSql('ALTER TABLE stock_transaction DROP effective_date');
        $this->addSql('ALTER TABLE stock_transaction DROP recorded_at');
        $this->addSql('ALTER TABLE stock_transaction DROP unit_cost');
        $this->addSql('ALTER TABLE stock_transaction DROP status');
        $this->addSql('ALTER TABLE stock_transaction DROP batch_id');
        $this->addSql('ALTER TABLE stock_transaction DROP ledger_entry_id');
        $this->addSql('ALTER TABLE "order" DROP subtotal');
        $this->addSql('ALTER TABLE "order" DROP tax_amount');
        $this->addSql('ALTER TABLE "order" DROP total_amount');
        $this->addSql('ALTER TABLE "order" DROP fulfillment_status');
        $this->addSql('ALTER TABLE "order" DROP fulfilled_at');
        $this->addSql('ALTER TABLE customer DROP payment_terms');
        $this->addSql('ALTER TABLE customer DROP ar_balance');
    }
}
