<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250805160533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_count (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE stock_count_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expected_qty NUMERIC(10, 2) DEFAULT NULL, counted_qty NUMERIC(10, 2) DEFAULT NULL, notes TEXT DEFAULT NULL, stock_count_id INT DEFAULT NULL, stock_target_id INT DEFAULT NULL, unit_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DF5F2B5F9CE6EC8 ON stock_count_item (stock_count_id)');
        $this->addSql('CREATE INDEX IDX_DF5F2B5F8D13ED8E ON stock_count_item (stock_target_id)');
        $this->addSql('CREATE INDEX IDX_DF5F2B5FF8BD700D ON stock_count_item (unit_id)');
        $this->addSql('CREATE TABLE stock_target (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, current_qty NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(16) DEFAULT NULL, item_id INT DEFAULT NULL, recipe_id INT DEFAULT NULL, base_unit_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C49FD6A126F525E ON stock_target (item_id)');
        $this->addSql('CREATE INDEX IDX_8C49FD6A59D8A214 ON stock_target (recipe_id)');
        $this->addSql('CREATE INDEX IDX_8C49FD6ACCBBC969 ON stock_target (base_unit_id)');
        $this->addSql('CREATE TABLE stock_target_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, min_qty NUMERIC(10, 2) DEFAULT NULL, max_qty NUMERIC(10, 2) DEFAULT NULL, stock_target_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_540E1C498D13ED8E ON stock_target_rule (stock_target_id)');
        $this->addSql('CREATE TABLE stock_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, use_type VARCHAR(32) DEFAULT NULL, qty NUMERIC(10, 2) DEFAULT NULL, reason TEXT DEFAULT NULL, stock_target_id INT DEFAULT NULL, unit_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ADF9A3E58D13ED8E ON stock_transaction (stock_target_id)');
        $this->addSql('CREATE INDEX IDX_ADF9A3E5F8BD700D ON stock_transaction (unit_id)');
        $this->addSql('ALTER TABLE stock_count_item ADD CONSTRAINT FK_DF5F2B5F9CE6EC8 FOREIGN KEY (stock_count_id) REFERENCES stock_count (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_count_item ADD CONSTRAINT FK_DF5F2B5F8D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_count_item ADD CONSTRAINT FK_DF5F2B5FF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_target ADD CONSTRAINT FK_8C49FD6A126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_target ADD CONSTRAINT FK_8C49FD6A59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_target ADD CONSTRAINT FK_8C49FD6ACCBBC969 FOREIGN KEY (base_unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_target_rule ADD CONSTRAINT FK_540E1C498D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_transaction ADD CONSTRAINT FK_ADF9A3E58D13ED8E FOREIGN KEY (stock_target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_transaction ADD CONSTRAINT FK_ADF9A3E5F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_count_item DROP CONSTRAINT FK_DF5F2B5F9CE6EC8');
        $this->addSql('ALTER TABLE stock_count_item DROP CONSTRAINT FK_DF5F2B5F8D13ED8E');
        $this->addSql('ALTER TABLE stock_count_item DROP CONSTRAINT FK_DF5F2B5FF8BD700D');
        $this->addSql('ALTER TABLE stock_target DROP CONSTRAINT FK_8C49FD6A126F525E');
        $this->addSql('ALTER TABLE stock_target DROP CONSTRAINT FK_8C49FD6A59D8A214');
        $this->addSql('ALTER TABLE stock_target DROP CONSTRAINT FK_8C49FD6ACCBBC969');
        $this->addSql('ALTER TABLE stock_target_rule DROP CONSTRAINT FK_540E1C498D13ED8E');
        $this->addSql('ALTER TABLE stock_transaction DROP CONSTRAINT FK_ADF9A3E58D13ED8E');
        $this->addSql('ALTER TABLE stock_transaction DROP CONSTRAINT FK_ADF9A3E5F8BD700D');
        $this->addSql('DROP TABLE stock_count');
        $this->addSql('DROP TABLE stock_count_item');
        $this->addSql('DROP TABLE stock_target');
        $this->addSql('DROP TABLE stock_target_rule');
        $this->addSql('DROP TABLE stock_transaction');
    }
}
