<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250404003554 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE recipe_tag_recipe (recipe_tag_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(recipe_tag_id, recipe_id))');
        $this->addSql('CREATE INDEX IDX_7AB77E7837CC7D30 ON recipe_tag_recipe (recipe_tag_id)');
        $this->addSql('CREATE INDEX IDX_7AB77E7859D8A214 ON recipe_tag_recipe (recipe_id)');
        $this->addSql('ALTER TABLE recipe_tag_recipe ADD CONSTRAINT FK_7AB77E7837CC7D30 FOREIGN KEY (recipe_tag_id) REFERENCES recipe_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_tag_recipe ADD CONSTRAINT FK_7AB77E7859D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_tag_recipe DROP CONSTRAINT FK_7AB77E7837CC7D30');
        $this->addSql('ALTER TABLE recipe_tag_recipe DROP CONSTRAINT FK_7AB77E7859D8A214');
        $this->addSql('DROP TABLE recipe_tag');
        $this->addSql('DROP TABLE recipe_tag_recipe');
    }
}
