<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123000111 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE katzen_waitlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, session_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, business_name VARCHAR(255) DEFAULT NULL, business_type VARCHAR(255) DEFAULT NULL, biggest_challenge TEXT DEFAULT NULL, software_expectations TEXT DEFAULT NULL, current_tools TEXT DEFAULT NULL, is_beta BOOLEAN DEFAULT NULL, preferred_contact_method VARCHAR(50) DEFAULT NULL, questionnaire_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, referral_source VARCHAR(100) DEFAULT NULL, utm_campaign VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE katzen_waitlist');
    }
}
