<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250629215329 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE public.sites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, is_production BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8DD1CB07A7A91E0B ON public.sites (domain)');
        $this->addSql('ALTER TABLE recipe_tag_recipe DROP CONSTRAINT fk_7ab77e7837cc7d30');
        $this->addSql('ALTER TABLE recipe_tag_recipe DROP CONSTRAINT fk_7ab77e7859d8a214');
        $this->addSql('DROP TABLE recipe_tag_recipe');
        $this->addSql('DROP TABLE recipe_tag');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_tag_recipe (recipe_tag_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY(recipe_tag_id, recipe_id))');
        $this->addSql('CREATE INDEX idx_7ab77e7859d8a214 ON recipe_tag_recipe (recipe_id)');
        $this->addSql('CREATE INDEX idx_7ab77e7837cc7d30 ON recipe_tag_recipe (recipe_tag_id)');
        $this->addSql('CREATE TABLE recipe_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE recipe_tag_recipe ADD CONSTRAINT fk_7ab77e7837cc7d30 FOREIGN KEY (recipe_tag_id) REFERENCES recipe_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_tag_recipe ADD CONSTRAINT fk_7ab77e7859d8a214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE public.sites');
    }
}
