<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251101215217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE customer_price_override (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, override_price NUMERIC(10, 2) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, customer_id INT NOT NULL, sellable_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_79D809389395C3F3 ON customer_price_override (customer_id)');
        $this->addSql('CREATE INDEX IDX_79D80938A75DE531 ON customer_price_override (sellable_id)');
        $this->addSql('CREATE INDEX idx_customer_price_override_dates ON customer_price_override (valid_from, valid_to)');
        $this->addSql('CREATE UNIQUE INDEX unique_customer_sellable_date ON customer_price_override (customer_id, sellable_id, valid_from)');
        $this->addSql('CREATE TABLE price_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, priority INT NOT NULL, stackable BOOLEAN NOT NULL, exclusive BOOLEAN NOT NULL, conditions JSON NOT NULL, actions JSON NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE price_rule_sellables (price_rule_id INT NOT NULL, sellable_id INT NOT NULL, PRIMARY KEY(price_rule_id, sellable_id))');
        $this->addSql('CREATE INDEX IDX_45FEE6181F68CB0D ON price_rule_sellables (price_rule_id)');
        $this->addSql('CREATE INDEX IDX_45FEE618A75DE531 ON price_rule_sellables (sellable_id)');
        $this->addSql('CREATE TABLE sellable (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(100) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, category VARCHAR(100) DEFAULT NULL, portion_multiplier NUMERIC(10, 4) DEFAULT NULL, base_price NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81DE4161F9038C4 ON sellable (sku)');
        $this->addSql('CREATE INDEX IDX_81DE4161727ACA70 ON sellable (parent_id)');
        $this->addSql('CREATE TABLE sellable_component (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity_multiplier NUMERIC(10, 4) NOT NULL, purpose VARCHAR(50) NOT NULL, sort_order INT NOT NULL, sellable_id INT NOT NULL, target_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CE58FD28A75DE531 ON sellable_component (sellable_id)');
        $this->addSql('CREATE INDEX IDX_CE58FD28158E0B66 ON sellable_component (target_id)');
        $this->addSql('CREATE TABLE sellable_modifier_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, required BOOLEAN NOT NULL, min_selections INT NOT NULL, max_selections INT DEFAULT NULL, sort_order INT NOT NULL, sellable_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_943BBA1A75DE531 ON sellable_modifier_group (sellable_id)');
        $this->addSql('CREATE TABLE sellable_modifier_group_modifiers (sellable_modifier_group_id INT NOT NULL, sellable_id INT NOT NULL, PRIMARY KEY(sellable_modifier_group_id, sellable_id))');
        $this->addSql('CREATE INDEX IDX_2B14E01C561F9537 ON sellable_modifier_group_modifiers (sellable_modifier_group_id)');
        $this->addSql('CREATE INDEX IDX_2B14E01CA75DE531 ON sellable_modifier_group_modifiers (sellable_id)');
        $this->addSql('CREATE TABLE sellable_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, variant_name VARCHAR(255) NOT NULL, sku VARCHAR(100) DEFAULT NULL, price_adjustment NUMERIC(10, 2) DEFAULT NULL, portion_multiplier NUMERIC(10, 4) DEFAULT NULL, sort_order INT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sellable_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF846445F9038C4 ON sellable_variant (sku)');
        $this->addSql('CREATE INDEX IDX_DF846445A75DE531 ON sellable_variant (sellable_id)');
        $this->addSql('ALTER TABLE customer_price_override ADD CONSTRAINT FK_79D809389395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_price_override ADD CONSTRAINT FK_79D80938A75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE price_rule_sellables ADD CONSTRAINT FK_45FEE6181F68CB0D FOREIGN KEY (price_rule_id) REFERENCES price_rule (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE price_rule_sellables ADD CONSTRAINT FK_45FEE618A75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable ADD CONSTRAINT FK_81DE4161727ACA70 FOREIGN KEY (parent_id) REFERENCES sellable (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable_component ADD CONSTRAINT FK_CE58FD28A75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable_component ADD CONSTRAINT FK_CE58FD28158E0B66 FOREIGN KEY (target_id) REFERENCES stock_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable_modifier_group ADD CONSTRAINT FK_943BBA1A75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable_modifier_group_modifiers ADD CONSTRAINT FK_2B14E01C561F9537 FOREIGN KEY (sellable_modifier_group_id) REFERENCES sellable_modifier_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable_modifier_group_modifiers ADD CONSTRAINT FK_2B14E01CA75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sellable_variant ADD CONSTRAINT FK_DF846445A75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_item ADD modifiers JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE order_item ADD sellable_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_item ADD sellable_variant_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09A75DE531 FOREIGN KEY (sellable_id) REFERENCES sellable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09FB54635E FOREIGN KEY (sellable_variant_id) REFERENCES sellable_variant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_52EA1F09A75DE531 ON order_item (sellable_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F09FB54635E ON order_item (sellable_variant_id)');
        $this->addSql('ALTER TABLE recipe ALTER default_price TYPE NUMERIC(18, 6)');
        $this->addSql('ALTER TABLE recipe ALTER default_price DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE customer_price_override DROP CONSTRAINT FK_79D809389395C3F3');
        $this->addSql('ALTER TABLE customer_price_override DROP CONSTRAINT FK_79D80938A75DE531');
        $this->addSql('ALTER TABLE price_rule_sellables DROP CONSTRAINT FK_45FEE6181F68CB0D');
        $this->addSql('ALTER TABLE price_rule_sellables DROP CONSTRAINT FK_45FEE618A75DE531');
        $this->addSql('ALTER TABLE sellable DROP CONSTRAINT FK_81DE4161727ACA70');
        $this->addSql('ALTER TABLE sellable_component DROP CONSTRAINT FK_CE58FD28A75DE531');
        $this->addSql('ALTER TABLE sellable_component DROP CONSTRAINT FK_CE58FD28158E0B66');
        $this->addSql('ALTER TABLE sellable_modifier_group DROP CONSTRAINT FK_943BBA1A75DE531');
        $this->addSql('ALTER TABLE sellable_modifier_group_modifiers DROP CONSTRAINT FK_2B14E01C561F9537');
        $this->addSql('ALTER TABLE sellable_modifier_group_modifiers DROP CONSTRAINT FK_2B14E01CA75DE531');
        $this->addSql('ALTER TABLE sellable_variant DROP CONSTRAINT FK_DF846445A75DE531');
        $this->addSql('DROP TABLE customer_price_override');
        $this->addSql('DROP TABLE price_rule');
        $this->addSql('DROP TABLE price_rule_sellables');
        $this->addSql('DROP TABLE sellable');
        $this->addSql('DROP TABLE sellable_component');
        $this->addSql('DROP TABLE sellable_modifier_group');
        $this->addSql('DROP TABLE sellable_modifier_group_modifiers');
        $this->addSql('DROP TABLE sellable_variant');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09A75DE531');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09FB54635E');
        $this->addSql('DROP INDEX IDX_52EA1F09A75DE531');
        $this->addSql('DROP INDEX IDX_52EA1F09FB54635E');
        $this->addSql('ALTER TABLE order_item DROP modifiers');
        $this->addSql('ALTER TABLE order_item DROP sellable_id');
        $this->addSql('ALTER TABLE order_item DROP sellable_variant_id');
        $this->addSql('ALTER TABLE recipe ALTER default_price TYPE NUMERIC(18, 6)');
        $this->addSql('ALTER TABLE recipe ALTER default_price SET DEFAULT \'0.00\'');
    }
}
