landing_page:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'profile/landing.html.twig'
features:
    path: /features
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'recipe_features.html.twig'	
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

uploads:
    path: /uploads/{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: '%kernel.project_dir%/public/uploads/{path}'
    requirements:
        path: .+